#This is a configuation file. Just define your variables here.

#The revised packet dataset for training. This will be generated by the C++ code that the 
#ClearTrail team will develop, to replace the create_flow_data() in create_flows.R
revised_pkts_trg <- "~/cleartrail_osn/SET3/TC1/RevisedPacketData_23_Feb_2016_TC1.csv"

#File where the human user saves the event names, start and end times. Please make sure the times are entered in a consistent manner (HH24:MM:SS),
#the first row has the following column names: Event, StartTime and EndTime, and the events are only of the following types: User Login, Tweet+Image,
#Tweet Only, ReTweet, Reply Tweet Text Only, Reply Tweet Text and Image, Like, User mouse drag end, User mouse wheel down.

events_trg <- "~/cleartrail_osn/SET3/TC1/23_Feb_2016_Set_I.csv"

#This is the file that contains the aggregate characteristics of individual timestamps. This will be generated by the C++ code that the 
#ClearTrail team will develop, to replace the label_packets() method in crf_sessions_and_flows.R
hidden_and_vis_states_trg <- "~/cleartrail_osn/SET3/TC1/hidden_and_vis_states_23_Feb_2016_Set_I.csv"

#For the following three files, the explanations are same as given above for the training data, the difference being they are for test data only.
revised_pkts_test <- "~/cleartrail_osn/SET3/TC2/RevisedPacketData_23_Feb_2016_TC2.csv"
events_test <- "~/cleartrail_osn/SET3/TC2/23_Feb_2016_Set_II.csv"
hidden_and_vis_states_test <- "~/cleartrail_osn/SET3/TC2/hidden_and_vis_states_23_Feb_2016_Set_II.csv"

#An intermediate output file with the predicted labels for each packet in the test dataset.
predicted_event_types <- "~/cleartrail_osn/SET3/TC2/predicted_event_types.csv"

#The binary file where the model is saved
saved_model <- "~/cleartrail_analytics/nb_model.rds"

#The final output file with event types and start and end times
start_end_event_file <- "~/cleartrail_osn/SET3/TC2/start_end_event.csv"

#File shows the actual vs the predicted events in a horizontal scale
image_file <- "~/cleartrail_analytics/figures/timeline_view_SET3_TC2.png"